# Generated by Django 4.2.7 on 2023-11-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('vendor_code', models.CharField(max_length=20, verbose_name='Артикул')),
                ('category', models.CharField(max_length=40, verbose_name='Категория')),
                ('sub_category', models.CharField(max_length=40, verbose_name='Подкатегория')),
                ('product_type', models.CharField(max_length=40, verbose_name='Вид изделия')),
                ('completeness', models.CharField(max_length=40, verbose_name='Комплектность')),
                ('gender', models.CharField(max_length=20, verbose_name='Пол')),
                ('season', models.CharField(max_length=20, verbose_name='Сезон')),
                ('material', models.CharField(max_length=40, verbose_name='Ткань/Материал верха')),
                ('compound', models.CharField(max_length=20, verbose_name='Состав')),
                ('density', models.CharField(max_length=20, verbose_name='Плотность/Толщина материала')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
