# Generated by Django 4.2.7 on 2023-11-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(verbose_name='Артикул', max_length=100)),
                ('category', models.TextField(verbose_name='Категория')),
                ('sub_category', models.TextField(verbose_name='Подкатегория')),
                ('product_type', models.TextField(verbose_name='Вид изделия')),
                ('completeness', models.TextField(verbose_name='Комплектность')),
                ('gender', models.TextField(verbose_name='Пол')),
                ('season', models.TextField(verbose_name='Сезон')),
                ('material', models.TextField(verbose_name='Ткань/Материал верха')),
                ('compound', models.TextField(verbose_name='Состав')),
                ('density', models.TextField(verbose_name='Плотность/Толщина материала')),
                ('color', models.TextField(verbose_name='Цвет')),
            ],
        ),
    ]
